### ISSUE TITLE
Change player TimeLine view so loan is displayed before contract

### ISSUE THREAD

**Issue by barillabartus** [avarixe/myfifa-vue#306]
Hey, I've been using this for the past week or so and it's an awesome thing to have when you are really hardcore and serious into one of your career mode saves so thank you for creating that! 

I've made one edit and I think that would do well to have it implemented in the 'main' project, repository, whatever - I'm super new to all this stuff.  

So, whenever you sign a player, contract him and loan him out on the same day (scenario is that you just buy a player and 'loan' him to his old club so he plays there for half a year or a year more, just like clubs do IRL), loan is displayed under the contract like:  
  
- Contracted
- Loaned
- Bought

I think it should've been

- Loaned
- Contracted
- Bought

Thank you for reading this.

**Comment by avarixe** [comment]
I do agree with you that in that situation, the current order doesn't work.

The way the application is currently set up, a Player must have an active Contract to be available in a Match. So, I acquire a Player on a Loan rather than a Transfer, I currently need to create a Contract representing the Player's time in my Team. In this case, it does make sense to display the Loan before the Contract.

I think the best way to resolve both cases (without rewriting the logic to determine a player's Active status) would be to sort the Player events by date, then the timestamp the record was created (e.g. `Loan#created_at`), and then by a set order.

I'll look into this further when I get the time to do so
